py_run:
	python3 *.py

go_run:
	go run *.go

cpp_run:
	g++ -o test test.cpp
	./test

cpp2_run:
	g++ -o test2 test_2.cpp
	./test2

cpp11_run:
	g++ -std=c++11 -o longest_substring longest_substring.cpp
	./longest_substring

clean:
	rm ./test
	rm ./test2
